name: 'Proxy Release to The OpenCollective'
description: 'Takes a release object and proxies it to The OpenCollective'
inputs:
  name: 
    description: 'The name of the GitHub Release'
    required: true
  body: 
    description: 'The body of the GitHub Release'
    required: true
  slug: 
    description: 'The slug of the OpenCollective account'
    required: true
  apiKey: 
    description: 'The OpenCollective API Key'
    required: true
outputs:
  id: 
    description: 'The id of the newly created update object'
runs:
  using: 'node12'
  main: 'index.js'
