name: 'Proxy Release to The OpenCollective'
description: 'Takes a release object and proxies it to The OpenCollective'
inputs:
  releaseId: 
    description: 'The id of the GitHub Release'
    required: true
  projectSlug:
    description: 'The slug of the GitHub project (e.g. sequelize/sequelize)'
    required: true
  ocSlug: 
    description: 'The slug of the OpenCollective account'
    required: true
  ocApiKey: 
    description: 'The OpenCollective API Key'
    required: true
  githubToken: 
    description: 'A GitHub Access Token'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
