# on: [push]

# jobs:
#   hello_world_job:
#     runs-on: ubuntu-latest
#     name: A job to say hello
#     steps:
#       # To use this repository's private action,
#       # you must check out the repository
#       - name: Checkout
#         uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: '14'
#       - run: npm install
#       - name: Hello world action step
#         uses: ./ # Uses an action in the root directory
#         id: hello
#         with:
#           releaseId: 56035002
#           projectSlug: sequelize/sequelize
#           ocSlug: sequelize
#           ocApiKey: ${{ secrets.OPEN_COLLECTIVE_KEY }}
#           githubToken: ${{ secrets.GITHUB_TOKEN }} 
